# Generated by Django 5.2.1 on 2025-05-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('setdate', models.DateTimeField(auto_now_add=True)),
                ('priority', models.BooleanField()),
            ],
            options={
                'verbose_name': 'One Off Task',
                'verbose_name_plural': 'One Off Tasks',
            },
        ),
        migrations.CreateModel(
            name='RepeatTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('lastdoneon', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Repeat Task',
                'verbose_name_plural': 'Repeat Tasks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Flatmate',
                'verbose_name_plural': 'Flatmates',
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='repeattask',
            name='assignedto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_tasks_assigned', to='api.user'),
        ),
        migrations.AddField(
            model_name='repeattask',
            name='lastdoneby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='oneofftask',
            name='assignedto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one_off_tasks_assigned', to='api.user'),
        ),
    ]
