services:
  - type: web
    name: app_51_web
    env: python
    region: frankfurt
    repo: https://github.com/yuhanwwu/app_51
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_51_db
          property: connectionString

databases:
  - name: app_51_db
    plan: free