services:
  - type: web
    name: app_51_db
    env: python
    region: frankfurt
    repo: https://github.com/yuhanwwu/app_51
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application -k uvicorn.workers.UvicornWorker
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_51_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: app_51_db
    plan: free