services:
  - type: web
    name: app_51_db
    env: python
    region: frankfurt
    repo: https://github.com/yuhanwwu/app_51
    branch: master
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_51_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - ADMIN_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
      - ADMIN_USERNAME: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
      - ADMIN_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
    
    releaseCommand: |
      python manage.py makemigrations
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; \nUser = get_user_model(); \nUser.objects.filter(username=\"$ADMIN_USERNAME\").exists() or User.objects.create_superuser(\"$ADMIN_USERNAME\", \"$ADMIN_EMAIL\", \"$ADMIN_PASSWORD\")" | python manage.py shell


databases:
  - name: app_51_db
    plan: free