// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEREmcPhTEm7MgfVxKUFugvycB26bZ-YA',
    appId: '1:1083791752141:web:03d4741e44d8b1e76ce284',
    messagingSenderId: '1083791752141',
    projectId: 'app51-lalapi',
    authDomain: 'app51-lalapi.firebaseapp.com',
    storageBucket: 'app51-lalapi.firebasestorage.app',
    measurementId: 'G-2GX064BCDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1dXxq9iyM9dzkHWWNvArsd-K5HE_DXGA',
    appId: '1:1083791752141:android:993a31bf71066ad96ce284',
    messagingSenderId: '1083791752141',
    projectId: 'app51-lalapi',
    storageBucket: 'app51-lalapi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgBY_ThPgKDp-OzAkIM6vGguMrOdUXy8g',
    appId: '1:1083791752141:ios:f3609ae4f8a848b96ce284',
    messagingSenderId: '1083791752141',
    projectId: 'app51-lalapi',
    storageBucket: 'app51-lalapi.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
