name: Build, Test, and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: # Add this section for manual triggering
    inputs:
      branch_to_deploy:
        description: 'Branch to deploy to GitHub Pages'
        required: true
        default: 'master' # Set a default to make regular manual deploys easier

permissions:
  contents: write
  pages: write

jobs:
  build-flutter:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:stable
    steps:
      - uses: actions/checkout@v4

      - name: Build Flutter Web
        run: |
          cd frontend
          flutter clean
          flutter pub get
          flutter build web --base-href=/app_51/
          cd ..
          mkdir -p public
          cp -r frontend/build/web/* public/

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: public

  flutter-test:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:stable
    steps:
      - uses: actions/checkout@v4
      - name: Run Flutter Tests
        run: |
          cd frontend
          flutter test

  # django-test:
  #   runs-on: ubuntu-latest
  #   container: python:3.11
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Backend Dependencies
  #       run: |
  #         pip install -r requirements.txt
  #         cd backend
  #         python manage.py test

  deploy-to-gh-pages:
    needs: build-flutter
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This step will also need to checkout the correct branch for pages to be properly deployed
          # Although peaceiris/actions-gh-pages@v3 often handles this, it's good practice
          ref: ${{ github.event.inputs.branch_to_deploy || github.ref_name }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: flutter-web
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public