name: Build and Deploy Flutter & Django

on:
  push:
    branches:
      - main
      - master  # in case you're still using master

jobs:
  compile-frontend:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:stable
    steps:
      - uses: actions/checkout@v3
      - name: Build Flutter Web
        run: |
          cd frontend
          flutter pub get
          flutter build web
          cd ..
          mkdir -p public
          cp -r frontend/build/web/* public/
          ls -l public

      - name: Upload Flutter Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web
          path: public/

  compile-backend:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          python3 -m compileall .

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-compiled
          path: backend/

  flutter-test:
    runs-on: ubuntu-latest
    container: ghcr.io/cirruslabs/flutter:stable
    steps:
      - uses: actions/checkout@v3
      - name: Run Flutter Tests
        run: |
          cd frontend
          flutter pub get
          flutter test

  django-test:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
      - name: Run Django Tests
        run: |
          cd backend
          pip install -r requirements.txt
          python manage.py test

    deploy-to-pages:
      runs-on: ubuntu-latest
      needs: compile-frontend
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Download Web Artifact
          uses: actions/download-artifact@v3
          with:
            name: flutter-web
            path: public

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
